CREATE TABLE IF NOT EXISTS User (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(32) NOT NULL,
    Cognome VARCHAR(32) NOT NULL,
    DataNascita DATE NOT NULL,
    NomeUtente VARCHAR(32) NOT NULL,
    Password CHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Role(
	id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Authority VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS UserRole(
	id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Userid int NOT NULL,
    Roleid int NOT NULL,
    FOREIGN KEY (Userid) REFERENCES User(id),
    FOREIGN KEY (Roleid) REFERENCES Role(id)
);

CREATE TABLE IF NOT EXISTS Project(
	id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(32) NOT NULL,
    Descrizione TEXT,
    Completato BOOL DEFAULT false,
    DataInizio DATETIME NOT NULL,
    DataCompletamento DATE NULL,
    DataScadenza DATE NOT NULL,
    Creatore int NOT NULL,
	FOREIGN KEY (Creatore) REFERENCES User(id)
);